Admin form firebase connection
ernestkamara/covid-19-sl pull request #26
Opened 2020-04-06 02:20 UTC by J4yM1l

admin form can now add data to firestore.

2020-04-07 05:12 UTC, bascoe10 approved these changes

2020-04-07 19:04 UTC, ernestkamara commented
FYI: Can you please summarise what has been done and what new plugins were added in your PR description.
I find this very useful before reviewing PRs.
Just my opinion.

2020-04-07 20:21 UTC, J4yM1l commented
Added a form where admin can be able to add test center details to database such as address, city with regional location if necessary and phone number. In other to access the form, type /admin on url.

2020-04-07 20:40 UTC, ernestkamara requested changes
See comments.

2020-04-07 20:40 UTC, ernestkamara commented on src/components/admin-form.js
> +        // this.handleChange = this.handleChange.bind(this);
Remove commented lines if not needed

2020-04-07 20:40 UTC, ernestkamara commented on src/components/admin-form.js
> +            console.log(crenditial.user.uid);
Remove this, we don’t want to expose this I’d

2020-04-07 20:49 UTC, ernestkamara commented
Submitting this form requires a valid admin account in my opinion . Deleting this submission would be hard since the data is being stored anonymously. Can you elaborate the use case here or on slack? Just making sure we need it and we’ll thought off.

2020-04-09 17:34 UTC, ernestkamara approved these changes

2020-04-11 02:55 UTC, J4yM1l commented
@ernestkamara, @bascoe10 -Requested changes has been made to the admin form plus a new input field was also added (hospitalName) which will be updated on the test-center table soon. In addition, form input is now validated for empty string or incorrect number format.

2020-04-11 13:36 UTC, ernestkamara approved these changes
Works!

2020-04-11 13:36 UTC, ernestkamara commented on src/components/test-centers.js
> +      const context = this
Is this an update to an existing document or an insertion? I haven't run this PR yet.

2020-04-11 16:11 UTC, J4yM1l commented on src/components/test-centers.js
> +      const context = this
Actually, neither, but it's for fetching. Those changes should have reflected on the test-center pr not here, maybe I might make a change on that later. Look at test center pr for full detail.

2020-04-12 00:27 UTC, closed without merging